info:
  component: Prediction MicroService

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: prediction
        
data:
  mongodb:
    host: localhost
    port: 27017
    database: prediction
    username: mongo
    password: admin
