info:
  component: Prediction MicroService

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: prediction
        
data:
  mongodb:
    host: localhost
    port: 27017
    database: prediction
    username: mongo
    password: admin

services:
  user:
    info: http://USERS/user/
  event:
    info: http://EVENTS/event/
  predictor:
      info: http://PREDICTORS/predictors/