server:
  port: 9008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
    
data:
  mongodb:
    host: localhost
    port: 27017
    database: prediction
    username: mongo
    password: admin
