---
info:
  component: Frontend

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true

spring:
  oauth2:
    resource:
      userInfoUri: http://auth:7777/credential
  datasource:
    initialization-fail-fast: true
    validation-query: SELECT 1
    continue-on-error: true
    schema: classpath:db-ddl.sql
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
