---
info:
  component: Frontend

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
