server:
  port: 7777

spring:
  oauth2:
    client:
      clientId: 397752094259-q4fpt4cseicsp10cpim3shj3q927074k.apps.googleusercontent.com
      clientSecret: 8unbHUMRF8RcYMwqibcTWSpi
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: query
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/