info:
  component: Championship MicroService

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  eureka:
    enabled: true

data:
  mongodb:
    host: localhost
    port: 27017
    database: championship
    username: mongo
    password: admin

spring:
  application:
    name: championships

usermicroservice:
    user-info: http://USERS/users/user/