server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user
  datasource:  
    url: jdbc:mariadb://localhost:3306/user
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver