server:
  port: 9003
  contextPath: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    resource:
      user: /api/user/**
      stripPrefix: false