version: '2'
services:
  config:
    restart: always
    image: apibol/config-microservice
    depends_on:
      - discovery
    ports:
      - 8001:8001
    networks:
      - backend

  discovery:
    restart: always
    image: apibol/discovery-microservice
    ports:
      - 8761:8761
    networks:
      - backend

  gateway:
    restart: always
    image: apibol/api-gateway-microservice
    ports:
      - 8888:8888
    networks:
      - backend
    depends_on:
      - config
      - discovery

  usermicro:
      restart: always
      image: apibol/user-microservice
      depends_on:
        - config
        - discovery
      networks:
        - backend

  rabbit:
    restart: always
    image: rabbitmq:3.6.0-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  dbinstance:
    restart: always
    image: mariadb
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=user
    networks:
      - backend

  authdb:
      restart: always
      image: mariadb
      expose:
        - 3307
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=auth
      networks:
        - backend

networks:
  backend:
    driver: bridge