version: '2'
services:
  config:
    restart: always
    image: claudioed/config-microservice
    depends_on:
      - discovery
    ports:
      - 8001:8001
    links:
        - discovery:discovery

  discovery:
    restart: always
    image: claudioed/discovery-microservice
    ports:
      - 8761:8761

  gateway:
    restart: always
    image: claudioed/api-gateway-microservice
    ports:
      - 8888:8888
    links:
      - config:config
      - discovery:discovery
    depends_on:
      - config
      - discovery

  rabbit:
    restart: always
    image: rabbitmq:3.6.0-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  dbinstance:
    restart: always
    image: mariadb
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=user