version: '2'
services:

  rabbit:
    restart: always
    image: rabbitmq:3.6.0-management
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  dbinstance:
    restart: always
    image: mariadb
    ports:
      - 3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=user
    networks:
      - backend

  authdb:
    restart: always
    image: mariadb
    ports:
      - 3307
    expose:
      - 3308
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=auth
    networks:
      - backend

  mongodb:
    restart: always
    image: mongo
    ports:
      - 27017
    expose:
      - 27017
    networks:
      - backend

  redis:
    restart: always
    image: redis
    ports:
      - 6379
    expose:
      - 6379
    networks:
      - backend

networks:
  backend:
    driver: bridge